version: '3.9'
services:

  elasticsearch:
    container_name: me_protocol_elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    restart: always
    environment:
      # - xpack.security.http.ssl=false
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    # cap_add:
    #   - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - protocol_backend

  kibana:
    container_name: me_protocol_kibana
    image: docker.elastic.co/kibana/kibana:8.10.0
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://me_protocol_elastic_search:9200
    ports:
      - 5601:5601
    networks:
      - protocol_backend

  # app:
  #   container_name: me_backend_app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - db
  #   restart: always
  #   volumes:
  #     - C:/Users/farouq.komolafe/Production/fullstack/business-portal-backend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   networks:
  #     - protocol_backend

  redis:
    container_name: me_protocol_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - protocol_backend

  db:
    container_name: me_protocol_db
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - protocol_backend
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - protocol_backend

volumes:
  elasticsearch-data-volume:
    driver: local

  pg-data:
    driver: local

  redis:
    driver: local

networks:
  protocol_backend:
    driver: bridge
