export const selectUser = {
  id: true,
  firstName: true,
  lastName: true,
  profileImage: true,
  coverImage: true,
  bio: true,
  location: true,
  website: true,
  username: true,
  private: true,
  showActivity: true,
  appType: true,
  isBusiness: true,
  showLocation: true,
  followingCount: true,
  followerCount: true,
  postCount: true,
  lastSeen: true,
  userState: true,
};
