import { selectUser } from "./helpers/selectUser";

export const selectEventCategory = {
  name: true,
  description: true,
  image: true,
  white_icon: true,
  black_icon: true,
  totalPosts: true,
  followerCount: true,
  id: true,
  createdAt: true,
  updatedAt: true,
};

export const selectEvent = {
  name: true,
  description: true,
  image: true,
  fileType: true,
  location: true,
  date: true,
  startTime: true,
  endTime: true,
  capacity: true,
  isPublished: true,
  isCancelled: true,
  isFeatured: true,
  isFree: true,
  isPaid: true,
  isSoldOut: true,
  isOnline: true,
  isPhysical: true,
  isPrivate: true,
  isPublic: true,
  eventCategoryId: true,
  eventCategory: selectEventCategory,
  userId: true,
  user: selectUser,
  hashtags: true,
  location_lat: true,
  location_lng: true,
  viewCount: true,
  likeCount: true,
  shareCount: true,
  commentCount: true,
  likers: true,
  discussionCount: true,
  guestVisiblity: true,
  going: true,
  maybeGoing: true,
  notGoing: true,
  id: true,
  createdAt: true,
  updatedAt: true,
};

export const selectFeed = {
  content: true,
  files: true,
  hashtags: true,
  userId: true,
  eventId: true,
  event: selectEvent,
  viewCount: true,
  commentCount: true,
  likers: true,
  likeCount: true,
  mentions: true,
  user: selectUser,
  id: true,
  createdAt: true,
  updatedAt: true,
};
