export enum OfferFilter {
  MOST_VIEWED = 'MOST_VIEWED',
  MOST_SALES = 'MOST_SALES',
  MOST_RECENT = 'MOST_RECENT',
  LOW_IN_STOCK = 'LOW_IN_STOCK',
}

export enum OfferSort {
  TRENDING = 'TRENDING',
  NEW = 'NEW',
  PRICE_HIGH_TO_LOW = 'PRICE_HIGH_TO_LOW',
  PRICE_LOW_TO_HIGH = 'PRICE_LOW_TO_HIGH',
  POPULAR = 'POPULAR',
  EXPIRING = 'EXPIRING',
}

export enum ProductFilter {
  MOST_RECENT = 'MOST_RECENT',
  LOW_IN_STOCK = 'LOW_IN_STOCK',
}
