/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull server-side'
 *
 * Required dependencies: @amplitude/analytics-node@^1.0.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: node.js:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/me-protocol/Consumer%20App%20(Development)/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/me-protocol/Consumer%20App%20(Development)/implementation/server-side)
 */

import * as amplitude from '@amplitude/analytics-node';

export type NodeClient = amplitude.Types.NodeClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
export type NodeOptions = amplitude.Types.NodeOptions;

export type Environment = 'consumerappdevelopment';

export const ApiKey: Record<Environment, string> = {
  consumerappdevelopment: '6a46088de95ef5ba923f50ce771dc3ac',
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: NodeOptions = {
  plan: {
    version: '1',
    branch: 'main',
    source: 'server-side',
    versionId: '26288ca4-12d0-49f2-8c2d-03691873d462',
  },
  ...{
    ingestionMetadata: {
      sourceName: 'node.js-typescript-ampli',
      sourceVersion: '2.0.0',
    },
  },
};

export interface LoadOptionsBase {
  disabled?: boolean;
}

export type LoadOptionsWithEnvironment = LoadOptionsBase & {
  environment: Environment;
  client?: { configuration?: NodeOptions };
};
export type LoadOptionsWithApiKey = LoadOptionsBase & {
  client: { apiKey: string; configuration?: NodeOptions };
};
export type LoadOptionsWithClientInstance = LoadOptionsBase & {
  client: { instance: NodeClient };
};

export type LoadOptions =
  | LoadOptionsWithEnvironment
  | LoadOptionsWithApiKey
  | LoadOptionsWithClientInstance;

export interface PointsReceivedProperties {
  brand: string;
  brand_category: string;
  brand_id: string;
  dollars: string;
  partnership: boolean;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  points: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  points_me_token: number;
}

export interface UserLoginProperties {
  login_method: string;
}

export interface UserSignUpProperties {
  registration_method: string;
}

export class PointsReceived implements BaseEvent {
  event_type = 'Points Received';

  constructor(public event_properties: PointsReceivedProperties) {
    this.event_properties = event_properties;
  }
}

export class UserLogin implements BaseEvent {
  event_type = 'User Login';

  constructor(public event_properties: UserLoginProperties) {
    this.event_properties = event_properties;
  }
}

export class UserLogout implements BaseEvent {
  event_type = 'User Logout';
}

export class UserSignUp implements BaseEvent {
  event_type = 'User SignUp';

  constructor(public event_properties: UserSignUpProperties) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: NodeClient;

  get client(): NodeClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    if (options && options.extra) {
      for (const [key, value] of Object.entries(options.user_properties)) {
        amplitudeIdentify.set(key, value);
      }
    }

    return this.amplitude!.identify(amplitudeIdentify, options);
  }

  /**
   * Track event
   *
   * @param userId The user's id.
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(userId: string | undefined, event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    return this.amplitude!.track(event, undefined, options);
  }

  flush(): PromiseResult<void> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Points Received
   *
   * [View in Tracking Plan](https://data.amplitude.com/me-protocol/Consumer%20App%20(Development)/events/main/latest/Points%20Received)
   *
   * This event tracks when a user receives points from a brand.
   *
   * Owner: Daniel Owolabi
   *
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. brand)
   * @param options Amplitude event options.
   */
  pointsReceived(
    userId: string | undefined,
    properties: PointsReceivedProperties,
    options?: EventOptions,
  ) {
    return this.track(userId, new PointsReceived(properties), options);
  }

  /**
   * User Login
   *
   * [View in Tracking Plan](https://data.amplitude.com/me-protocol/Consumer%20App%20(Development)/events/main/latest/User%20Login)
   *
   * This event tracks when a user logs into the consumer app successfully.
   *
   * Owner: Daniel Owolabi
   *
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. login_method)
   * @param options Amplitude event options.
   */
  userLogin(
    userId: string | undefined,
    properties: UserLoginProperties,
    options?: EventOptions,
  ) {
    return this.track(userId, new UserLogin(properties), options);
  }

  /**
   * User Logout
   *
   * [View in Tracking Plan](https://data.amplitude.com/me-protocol/Consumer%20App%20(Development)/events/main/latest/User%20Logout)
   *
   * This event tracks when a user logs out of the consumer app.
   *
   * Owner: Daniel Owolabi
   *
   * @param userId The user's ID.
   * @param options Amplitude event options.
   */
  userLogout(
    userId: string | undefined,
    options?: EventOptions,
  ) {
    return this.track(userId, new UserLogout(), options);
  }

  /**
   * User SignUp
   *
   * [View in Tracking Plan](https://data.amplitude.com/me-protocol/Consumer%20App%20(Development)/events/main/latest/User%20SignUp)
   *
   * Event to track when a new user registers on the consumer app.
   *
   * Owner: Daniel Owolabi
   *
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. registration_method)
   * @param options Amplitude event options.
   */
  userSignUp(
    userId: string | undefined,
    properties: UserSignUpProperties,
    options?: EventOptions,
  ) {
    return this.track(userId, new UserSignUp(properties), options);
  }
}

export const ampli = new Ampli();
